# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-14 22:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birthday', models.DateField(null=True)),
                ('weight', models.IntegerField(null=True)),
                ('breed', models.CharField(max_length=100)),
                ('potty_trained', models.BooleanField()),
                ('bio', models.TextField(null=True)),
                ('activity', models.CharField(choices=[('LO', 'Not active'), ('MD', 'Somewhat active'), ('HI', 'Very active')], max_length=2)),
                ('temperament_kids', models.CharField(choices=[('LO', 'Prefers to be left alone'), ('MD', 'Good with small groups'), ('HI', 'Good with any size groups')], max_length=2)),
                ('temperament_dogs', models.CharField(choices=[('LO', 'Prefers to be left alone'), ('MD', 'Good with small groups'), ('HI', 'Good with any size groups')], max_length=2)),
                ('temperament_strangers', models.CharField(choices=[('LO', 'Prefers to be left alone'), ('MD', 'Good with small groups'), ('HI', 'Good with any size groups')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='woofer.Dogs')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=30)),
                ('zipcode', models.IntegerField()),
                ('start_day', models.DateField()),
                ('start_time', models.TimeField()),
                ('duration', models.DurationField()),
                ('description', models.TextField()),
                ('location', models.CharField(choices=[('I', 'Indoors'), ('O', 'Outdoors')], max_length=1)),
                ('activity', models.CharField(choices=[('LO', 'Not active'), ('MD', 'Somewhat active'), ('HI', 'Very active')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='WooferUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.IntegerField(null=True)),
                ('zipcode', models.IntegerField()),
                ('birthday', models.DateField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='events',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='woofer.WooferUser'),
        ),
        migrations.AddField(
            model_name='eventattendance',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='woofer.Events'),
        ),
        migrations.AddField(
            model_name='dogs',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='woofer.WooferUser'),
        ),
    ]
