# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-05 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woofer', '0007_auto_20160404_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendance_cap',
            field=models.IntegerField(default=0),
        ),
    ]
