# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-05 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woofer', '0008_event_attendance_cap'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='attendance_cap',
            field=models.IntegerField(default=1),
        ),
    ]
