# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-06 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woofer', '0009_auto_20160405_2031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventattendance',
            old_name='dog_id',
            new_name='dog',
        ),
        migrations.RenameField(
            model_name='eventattendance',
            old_name='event_id',
            new_name='event',
        ),
        migrations.RemoveField(
            model_name='event',
            name='attendance',
        ),
        migrations.AlterField(
            model_name='event',
            name='attendance_cap',
            field=models.IntegerField(default=0),
        ),
    ]
