# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-28 00:23
from __future__ import unicode_literals

from django.db import migrations, models
import woofer.validators


class Migration(migrations.Migration):

    dependencies = [
        ('woofer', '0010_auto_20160406_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='birthday',
            field=models.DateField(blank=True, null=True, validators=[woofer.validators.validate_date]),
        ),
        migrations.AlterField(
            model_name='event',
            name='attendance_cap',
            field=models.IntegerField(default=0, validators=[woofer.validators.validate_greater_than_or_equal_zero]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, null=True, validators=[woofer.validators.validate_date]),
        ),
    ]
