""" This is part of the autogenerated django code. """
from django.apps import AppConfig


class WooferConfig(AppConfig):
    """ This class holds configuration information for the Woofer Django app."""
    name = 'woofer'
